spring.application.name=java-ee-starter

# 数据库配置
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis配置
# classpath对应resources的目录
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.zjq.java_ee_starter.entity
mybatis.configuration.jdbc-type-for-null=NULL

# 打开MyBatis相关日志
logging.level.org.apache.ibatis=TRACE
logging.level.org.mybatis=TRACE
logging.level.org.mybatis.spring=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.com.zjq.java_ee_starter.mapper=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.beans.factory=DEBUG
logging.level.org.springframework.context.config=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true