@startuml
left to right direction
actor 用户
actor 管理员

rectangle 图书管理系统 {
    用户 -- (登录)
    用户 -- (注册)
    用户 -- (退出)
    用户 -- (查询图书)
    用户 -- (借阅图书)
    用户 -- (归还图书)
    
    管理员 -- (管理图书)
    管理员 -- (管理用户)
    管理员 -- (查看借阅记录)
}
@enduml